name: Content Automation Pipeline

# Trigger workflow on push to main branch or pull request
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Step 4: Run the pipeline
      - name: Run Content Automation
        run: python src/main.py

      # Step 5: Print success message
      - name: Print success
        run: echo "✅ SUCCESS: Pipeline completed!"
